/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import Tarjetas.*;
import funcionalidades.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class CrearTarjetas extends javax.swing.JFrame {
    DefaultTableModel dfm;
    Tarjetas[] tarjetas;
    int contTarjetas = 0;
    JuegoBoard juegoC;
    /**
     * Creates new form CrearTarjetas
     */
    public CrearTarjetas(JuegoBoard juegoC) {
        initComponents();
        contTarjetas = 0;
        setVisibleJPane9(false);
        dfm = (DefaultTableModel) tableLista.getModel();
        this.juegoC = juegoC;
        generarGrupos();
        leerDatos();        
    }
    private void generarGrupos(){
        
        String[] gruposTT = juegoC.getGrupoTT();
        for (int i = 0; i < juegoC.getGrupoTT().length; i++) {
            cmbGrupos.addItem(gruposTT[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipos = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCantTarjetas = new javax.swing.JTextField();
        jPanePerzonalizada = new javax.swing.JPanel();
        checkPremio = new javax.swing.JCheckBox();
        checkMulta = new javax.swing.JCheckBox();
        checkMover = new javax.swing.JCheckBox();
        checkPerder = new javax.swing.JCheckBox();
        checkVayaCarcel = new javax.swing.JCheckBox();
        checkCaminar = new javax.swing.JCheckBox();
        checkPagoPlayer = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLista = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbGrupos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Crear Tarjetas");

        jLabel2.setText("Tipo de tarjeta");

        cmbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caminar", "Premio", "Multa", "Pago a Jugadores", "Mover a Casilla", "Perder Turno", "Salga de la Carcel", "Vaya a la Carcel", "Tarjeta Personalizada" }));
        cmbTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiposActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar a la lista");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad de copias de la tarjeta");

        checkPremio.setText("Premio");

        checkMulta.setText("Multa");

        checkMover.setText("Mover a Casilla");

        checkPerder.setText("Perder Turno");

        checkVayaCarcel.setText("Vaya a la Carcel");

        checkCaminar.setText("Caminar");

        checkPagoPlayer.setText("Pago a Jugadores");

        javax.swing.GroupLayout jPanePerzonalizadaLayout = new javax.swing.GroupLayout(jPanePerzonalizada);
        jPanePerzonalizada.setLayout(jPanePerzonalizadaLayout);
        jPanePerzonalizadaLayout.setHorizontalGroup(
            jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanePerzonalizadaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkMulta)
                    .addComponent(checkPremio)
                    .addComponent(checkCaminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanePerzonalizadaLayout.createSequentialGroup()
                        .addGroup(jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkMover)
                            .addComponent(checkPerder))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanePerzonalizadaLayout.createSequentialGroup()
                        .addComponent(checkPagoPlayer)
                        .addContainerGap())))
            .addGroup(jPanePerzonalizadaLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(checkVayaCarcel)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanePerzonalizadaLayout.setVerticalGroup(
            jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanePerzonalizadaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCaminar)
                    .addComponent(checkPagoPlayer))
                .addGap(31, 31, 31)
                .addGroup(jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPremio)
                    .addComponent(checkMover))
                .addGap(34, 34, 34)
                .addGroup(jPanePerzonalizadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMulta)
                    .addComponent(checkPerder))
                .addGap(38, 38, 38)
                .addComponent(checkVayaCarcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIpo", "cantidad de copias", "Mensaje", "grupo"
            }
        ));
        jScrollPane1.setViewportView(tableLista);

        jLabel4.setText("Tarjetas creadas");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Grupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(73, 73, 73))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCantTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                        .addComponent(cmbGrupos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanePerzonalizada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(txtCantTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jPanePerzonalizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnGuardar))
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiposActionPerformed
        // TODO add your handling code here:
        if (cmbTipos.getSelectedItem().toString().equals("Tarjeta Personalizada")) {
            setVisibleJPane9(true);            
        }else{
            setVisibleJPane9(false);
        }
            
    }//GEN-LAST:event_cmbTiposActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:+
//        MenuCrear menu = new MenuCrear();
          this.setVisible(false);          
//        menu.setLocationRelativeTo(null);
//        menu.setVisible(true);        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void leerDatos(){
        if (leerContenido()) {
            tarjetas = juegoC.getTarjetas();
            contTarjetas = tarjetas.length;
            for (int i = 0; i < tarjetas.length; i++) {
            String data[] = {tarjetas[i].getTipoTarjeta(),String.valueOf(tarjetas[i].getTarjeta().getCantCopias()),tarjetas[i].getTarjeta().getMensaje(), tarjetas[i].getTarjeta().getGrupoTT()
            };
            dfm.addRow(data);
        }
        }
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try{
            String mensaje;
            if (isEmpty() && Integer.parseInt(txtCantTarjetas.getText()) > 0) {
                JOptionPane.showMessageDialog(null, "Debe colocar la cantidad de copias de la tarjeta mayor a 0");
            } else{
                if (cmbTipos.getSelectedItem().toString().equalsIgnoreCase("Vaya a la Carcel")) {
                    mensaje = "vaya a la carcel";
                    agregarTarjeta(mensaje);
                } else if (cmbTipos.getSelectedItem().toString().equalsIgnoreCase("Tarjeta Personalizada")) {
                    mensaje = JOptionPane.showInputDialog(null,"Escriba su mensaje");

                    verificarSeleccion();
                    agregarTarjeta(mensaje);
                } else{
                    mensaje = JOptionPane.showInputDialog(null,"Escriba su mensaje");
                    agregarTarjeta(mensaje);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hagalo bien \n rellene todos los espacios", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void agregarTarjeta(String mensaje){
        String tipo = cmbTipos.getSelectedItem().toString();
            Tarjetas tarjeta = new Tarjetas();
            TarjetasPro tarjetaPro = new TarjetasPro(mensaje,Integer.parseInt(txtCantTarjetas.getText()), cmbGrupos.getSelectedItem().toString());
            tarjetaPro = tarjeta.verificarTipo(tipo,mensaje,txtCantTarjetas, juegoC, cmbGrupos.getSelectedItem().toString());            
            contTarjetas++;
            redimensionar(tarjetaPro,tipo);
            listado();
            JOptionPane.showMessageDialog(null, "Agregado");
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tarjetas Agredadas Exitosamentes");
        this.setVisible(false);
        juegoC.setTarjetas(tarjetas);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void setVisibleJPane9(boolean estado){
        jPanePerzonalizada.setVisible(estado);
    }
    private boolean isEmpty(){
        return txtCantTarjetas.getText().replaceAll(" ", "").isEmpty();
    }
    
    
    private void listado(){        
        //Limpiar listado
       int cantRow = tableLista.getRowCount();
        if (contTarjetas > 1 ) {
            for (int i = cantRow-1; i >= 0; i--) {
                dfm.removeRow(i);
            }
        }        
        //Agregar listado
        for (int i = 0; i < tarjetas.length; i++) {
            String data[] = {tarjetas[i].getTipoTarjeta(),String.valueOf(tarjetas[i].getTarjeta().getCantCopias()),tarjetas[i].getTarjeta().getMensaje(), tarjetas[i].getTarjeta().getGrupoTT()
            };
            dfm.addRow(data);
        }
//        String data[] = {tipo,String.valueOf(cantCopias),mensaje};        
//        dfm.addRow(data);
    }
    private void redimensionar(TarjetasPro tarjeta,String tipo){
        if (contTarjetas == 1) {
            tarjetas = new Tarjetas[1];
            tarjetas[0] = new Tarjetas(tarjeta,tipo);
        } else{
            Tarjetas[] tarjetas1 = new Tarjetas[tarjetas.length];
            for (int i = 0; i < tarjetas.length; i++) {
                tarjetas1[i] = tarjetas[i];
            }
            tarjetas = new Tarjetas[contTarjetas];
            for (int i = 0; i < tarjetas1.length; i++) {
                tarjetas[i] = tarjetas1[i];
            }
             tarjetas[contTarjetas-1] = new Tarjetas(tarjeta,tipo);
        }
    }
    private boolean leerContenido(){
        return (juegoC.getTarjetas() != null);
    }
    private void verificarSeleccion(){
        if (checkCaminar.isSelected()) {
            TarjetaPersonalizada.caminar = true;
        } else{
             TarjetaPersonalizada.caminar = false;
        }
        if (checkMover.isSelected()) {
             TarjetaPersonalizada.mover = true;
        }else{
             TarjetaPersonalizada.mover = false;
        }
        if (checkMulta.isSelected()) {
             TarjetaPersonalizada.multa = true;
        }else{
            TarjetaPersonalizada.multa = false;
        }
        if (checkPagoPlayer.isSelected()) {
             TarjetaPersonalizada.pagoJugadores = true;
        }else{
            TarjetaPersonalizada.pagoJugadores = false;
        }
        if (checkPerder.isSelected()) {
             TarjetaPersonalizada.perderTurno = true;
        }else{
            TarjetaPersonalizada.perderTurno = false;
        }
        if (checkPremio.isSelected()) {
             TarjetaPersonalizada.premio = true;
        }else{
            TarjetaPersonalizada.premio = false;
        }
        if (checkVayaCarcel.isSelected()) {
             TarjetaPersonalizada.vayaCarcel = true;
        }else{
             TarjetaPersonalizada.vayaCarcel = false;
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox checkCaminar;
    private javax.swing.JCheckBox checkMover;
    private javax.swing.JCheckBox checkMulta;
    private javax.swing.JCheckBox checkPagoPlayer;
    private javax.swing.JCheckBox checkPerder;
    private javax.swing.JCheckBox checkPremio;
    private javax.swing.JCheckBox checkVayaCarcel;
    private javax.swing.JComboBox<String> cmbGrupos;
    private javax.swing.JComboBox<String> cmbTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanePerzonalizada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLista;
    private javax.swing.JTextField txtCantTarjetas;
    // End of variables declaration//GEN-END:variables
}
