/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import funcionalidades.*;
import java.awt.Container;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author chejohrpp
 */
public class DiseñoGeneralidad extends javax.swing.JFrame {
    Jugadores[] jugadores;
    AddJugadores[] adJugadores;
    Generalidades general;
    
    /**
     * Creates new form DiseñoGeneralidad
     */
    
    public DiseñoGeneralidad(JuegoBoard juegoC) {
        initComponents();
//        jugadores = new Jugadores[cantJugadores];
//        adJugadores = new AddJugadores[cantJugadores];
//        generar(jPanel1,cantJugadores,juegoC);
        cargarDatos(juegoC);
        crearBtnSave(juegoC);
        btnGuardar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPorcetajeInteres = new javax.swing.JTextField();
        txtCantVuelta = new javax.swing.JTextField();
        txtNombreGame = new javax.swing.JTextField();
        txtDados = new javax.swing.JTextField();
        txtCantInicial = new javax.swing.JTextField();
        txtLimiteHoteles = new javax.swing.JTextField();
        txtLimiteCasas = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantJugadores = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad de dinero Inicial");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad de dinero por vuelta");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("LImites de casas");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Limites de hoteles");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Porcentaje de interes por hipoteca");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("Cantidad de dados a utilizar");

        txtNombreGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreGameActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel8.setText("Configuracion General");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Nombre del Juego");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Cantidad de jugadores");

        jLabel10.setText("Entre 2 a 6");

        jLabel11.setText("Entre 1 a 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addContainerGap(203, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)
                                .addComponent(jLabel9))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLimiteHoteles)
                            .addComponent(txtDados)
                            .addComponent(txtCantVuelta)
                            .addComponent(txtLimiteCasas)
                            .addComponent(txtCantInicial)
                            .addComponent(txtPorcetajeInteres)
                            .addComponent(txtNombreGame, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtCantJugadores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCantVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7))
                            .addComponent(txtDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtLimiteCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLimiteHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPorcetajeInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //MenuCrear menu = new MenuCrear();
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);        
//        menu.setLocationRelativeTo(null);
//        menu.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void crearBtnSave(JuegoBoard juegoC){
        btnSave = new javax.swing.JButton();
        btnSave.setText("Guardar");
        btnSave.setBounds(btnGuardar.getBounds());
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt,juegoC);
            }
        });
        add(btnSave);
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt, JuegoBoard juegoC){
        try{
            if (esVacia() && respetarLimites()) {
    //            for (int i = 0; i < adJugadores.length; i++) {
    //                jugadores[i] = adJugadores[i].getNewJugadores();                
    //            }
                general = new Generalidades(txtNombreGame.getText(),Integer.parseInt(txtCantInicial.getText()),
                        Integer.parseInt(txtCantVuelta.getText()),Integer.parseInt(txtDados.getText()),Integer.parseInt(txtLimiteCasas.getText())
                        ,Integer.parseInt(txtLimiteHoteles.getText()),Double.parseDouble(txtPorcetajeInteres.getText()),Integer.parseInt(txtCantJugadores.getText()));
                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                this.setVisible(false);
                juegoC.setGeneral(general);
                //juegoC.setJugadores(jugadores);
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese bien los datos","Error",JOptionPane.ERROR_MESSAGE);
        }   
        
    }
    private boolean respetarLimites(){
        if (Integer.parseInt(txtCantJugadores.getText()) < 7 && Integer.parseInt(txtCantJugadores.getText()) > 1 && Integer.parseInt(txtDados.getText()) < 4 && Integer.parseInt(txtDados.getText()) > 0) {
            return true;
        } 
        JOptionPane.showMessageDialog(null, "Debe respetar los parametros");
        return false;
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreGameActionPerformed

    
//    private void generar(Container panel,int canJugadores, JuegoBoard juegoC){ 
//        Jugadores[] jugador = juegoC.getJugadores();
//        for (int i = 0; i < canJugadores; i++) {            
//            AddJugadores addJugadores = new AddJugadores(i);
//            panel.add(addJugadores.getJugador());
//            panel.add(addJugadores.getNombre());
//            addJugadores.getFormat(i+1);
//            if (leerContenido(juegoC)) {                
//                addJugadores.getNombre().setText(jugador[i].getNombre());
//            }            
//            adJugadores[i] = addJugadores;            
//        }   
//    }
    private boolean esVacia(){
//        for (AddJugadores jugador : adJugadores) {
//            if (jugador.isEmpty()) {
//                JOptionPane.showMessageDialog(null, "Tiene que llenar todos los espacios");
//                return false;                
//            }
//        }
        if (txtNombreGame.getText().replaceAll(" ", "").isEmpty() || txtCantInicial.getText().replaceAll(" ", "").isEmpty() ||
                txtCantVuelta.getText().replaceAll(" ", "").isEmpty()  || txtDados.getText().replaceAll(" ", "").isEmpty() || 
                txtLimiteCasas.getText().replaceAll(" ", "").isEmpty() || txtLimiteHoteles.getText().replaceAll(" ", "").isEmpty() || txtPorcetajeInteres.getText().replaceAll(" ", "").isEmpty() ||
                txtCantJugadores.getText().replaceAll(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que llenar todos los espacios");
            return false;
        }
        return true;
    }
    private boolean leerContenido(JuegoBoard juegoC){
        return (juegoC.getGeneral() != null);
    }
    private void cargarDatos(JuegoBoard juegoC){
        if (leerContenido(juegoC)) {
            txtNombreGame.setText(juegoC.getGeneral().getNombreJuego());
            txtCantInicial.setText(String.valueOf(juegoC.getGeneral().getCantInicial()));
            txtCantVuelta.setText(String.valueOf(juegoC.getGeneral().getCantVuelta()));
            txtDados.setText(String.valueOf(juegoC.getGeneral().getCantDados()));
            txtLimiteCasas.setText(String.valueOf(juegoC.getGeneral().getLimiteCasas()));
            txtLimiteHoteles.setText(String.valueOf(juegoC.getGeneral().getLimiteHoteles()));
            txtPorcetajeInteres.setText(String.valueOf(juegoC.getGeneral().getPorcentajeHipoteca()));
            txtCantJugadores.setText(String.valueOf(juegoC.getGeneral().getCantJugadores()));
            
        }
    }

    private javax.swing.JButton btnSave;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantInicial;
    private javax.swing.JTextField txtCantJugadores;
    private javax.swing.JTextField txtCantVuelta;
    private javax.swing.JTextField txtDados;
    private javax.swing.JTextField txtLimiteCasas;
    private javax.swing.JTextField txtLimiteHoteles;
    private javax.swing.JTextField txtNombreGame;
    private javax.swing.JTextField txtPorcetajeInteres;
    // End of variables declaration//GEN-END:variables
}
