/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import Casillas.CasillaPropiedad;
import Casillas.CasillaTLugar;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author chejohrpp
 */
public class DPropiedad extends javax.swing.JFrame {
    private JButton boton;
    private CasillaTLugar casillaLugar;
    private String nombre;
    private int costo;
    /**
     * Creates new form DPropiedad
     */
    public DPropiedad(CasillaTLugar casillaLugar, JButton boton, String nombre, int costo) {
        initComponents();
        botonSave();
        this.casillaLugar = casillaLugar;
        this.boton = boton;
        this.nombre = nombre;
        this.costo = costo;
        agregarGrupo();
    }
    private void agregarGrupo(){
        if (MenuCrear.gruposPropiedad != null) {
            for (int i = 0; i < MenuCrear.gruposPropiedad.length; i++) {
                cmbGrupoPro.addItem(MenuCrear.gruposPropiedad[i]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCostoPropiedad2 = new javax.swing.JTextField();
        txtCostoEstancia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCostoEsCasa = new javax.swing.JTextField();
        txtCostoEsHotel = new javax.swing.JTextField();
        txtCostoCasa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCostoHotel = new javax.swing.JTextField();
        cmbGrupoPro = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 31)); // NOI18N
        jLabel3.setText("Configurar Propiedad");

        txtCostoEsHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoEsHotelActionPerformed(evt);
            }
        });

        txtCostoCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoCasaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Costo de estancia");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Precio de casa");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("Costo de estancia por casa");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Precio de hotel");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Costo de estancia por hotel");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Grupo de propiedad");

        btnAgregar.setText("Agregar un grupo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCostoEstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(txtCostoEsCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(txtCostoEsHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(txtCostoCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCostoHotel)
                                    .addComponent(cmbGrupoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCostoEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCostoEsCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(txtCostoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCostoEsHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCostoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbGrupoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoCasaActionPerformed

    private void txtCostoEsHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoEsHotelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCostoEsHotelActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here: 
        String nuevo = JOptionPane.showInputDialog("Ingrese el nuevo grupo");
        cmbGrupoPro.addItem(nuevo);
        redimensionar(nuevo);
    }//GEN-LAST:event_btnAgregarActionPerformed

 
    private void redimensionar(String nuevo){
        if (MenuCrear.gruposPropiedad == null) {
            MenuCrear.gruposPropiedad = new String[1];
            MenuCrear.gruposPropiedad[0] = nuevo;
        } else {
            String[] aux = new String[MenuCrear.gruposPropiedad.length];
            for (int i = 0; i < aux.length; i++) {
                aux[i] = MenuCrear.gruposPropiedad[i];
            }
            MenuCrear.gruposPropiedad = new String[aux.length+1];
            for (int i = 0; i < aux.length; i++) {
                MenuCrear.gruposPropiedad[i] = aux[i];
            }
            MenuCrear.gruposPropiedad[aux.length] = nuevo;
        }
    }
    public boolean todoLlenoBIen(){
        if (txtCostoEstancia.getText() != null && txtCostoEsCasa.getText() != null && txtCostoCasa.getText() != null && txtCostoEsHotel.getText() != null && txtCostoHotel.getText() != null &&
                cmbGrupoPro.getSelectedItem() != null) {
            return true;
        }
        return false;
    }
    private void botonSave(){
        btnSave = new javax.swing.JButton();
        btnSave.setText("Guardar");
        btnSave.setBounds(326, 490, 62, 30);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSaveActionPerformed(evt);
            }
        });
        add(btnSave);
    }
    public void botonSaveActionPerformed(java.awt.event.ActionEvent evt){
        if (todoLlenoBIen()) {
//            casillaLugar = new CasillaTLugar(Integer.parseInt(txtCostoEstancia.getText()), Integer.parseInt(txtCostoEsCasa.getText()),  Integer.parseInt(txtCostoEsHotel.getText()),
//             Integer.parseInt(txtCostoCasa.getText()),  Integer.parseInt(txtCostoHotel.getText()), cmbGrupoPro.getSelectedItem().toString());            
            casillaLugar.setConstoEstanciaHotel(Integer.parseInt(txtCostoEsHotel.getText()));
            casillaLugar.setCostoEstancia(Integer.parseInt(txtCostoEstancia.getText()));
            casillaLugar.setCostoEstanciaCasa( Integer.parseInt(txtCostoEsCasa.getText()));
            casillaLugar.setGrupoPropiedad(cmbGrupoPro.getSelectedItem().toString());
            casillaLugar.setPrecioCasa(Integer.parseInt(txtCostoCasa.getText()));
            casillaLugar.setPrecioHotel( Integer.parseInt(txtCostoHotel.getText()));
            config();
            this.setVisible(false);                       
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
        
    }
        public void config(){
        boton.setText(nombre+" \n $"+costo);
        boton.setOpaque(true);
        boton.setForeground(Color.pink);
        boton.setBackground(Color.PINK); 
        try{
            boton.setToolTipText(nombre+" \n $"+costo +" tipo:"+ casillaLugar.getGrupoPropiedad());    
        } catch (Exception e){
            System.out.println("propiedad");
        }        
        boton.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
    }
    
    private javax.swing.JButton btnSave;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbGrupoPro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCostoCasa;
    private javax.swing.JTextField txtCostoEsCasa;
    private javax.swing.JTextField txtCostoEsHotel;
    private javax.swing.JTextField txtCostoEstancia;
    private javax.swing.JTextField txtCostoHotel;
    private javax.swing.JTextField txtCostoPropiedad2;
    // End of variables declaration//GEN-END:variables
}
