/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import Excepciones.Exceptions;
import LecturaYEscritura.RnWCrearJuego;
import funcionalidades.*;
import java.awt.HeadlessException;
import javax.swing.*;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author chejohrpp
 */
public class MenuCrear extends javax.swing.JFrame {
    public JuegoBoard juegoC;
    public static String gruposPropiedad[] = null;
    public static String grupoTT[] = null;
    /**
     * Creates new form MenuCrear
     */
    public MenuCrear() {
        initComponents();
        juegoC = new JuegoBoard();
    }
    public void setLblTittle(String text){
        this.lblTittle.setText(text);
    }
    public MenuCrear(JuegoBoard juegoC){
        initComponents();
        this.juegoC = juegoC;
        gruposPropiedad = juegoC.getGruposPropiedad();
        grupoTT = juegoC.getGrupoTT();
        this.lblTittle.setText("Editar Juego");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittle = new javax.swing.JLabel();
        btnGeneral = new javax.swing.JButton();
        btnTablero = new javax.swing.JButton();
        btnTarjetas = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTittle.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        lblTittle.setText("Crear Juego");

        btnGeneral.setText("Configuracion General");
        btnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralActionPerformed(evt);
            }
        });

        btnTablero.setText("Diseño del Tablero");
        btnTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroActionPerformed(evt);
            }
        });

        btnTarjetas.setText("Diseño de tarjetas");
        btnTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetasActionPerformed(evt);
            }
        });

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(lblTittle)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnSave)
                .addGap(134, 134, 134)
                .addComponent(btnVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblTittle)
                .addGap(57, 57, 57)
                .addComponent(btnGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnVerificar))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroActionPerformed
        // TODO add your handling code here:
        
        if (juegoC.getTablero() == null) {
            DiseñoTablero diseñoTablero = new DiseñoTablero(juegoC);
            diseñoTablero.setLocationRelativeTo(null);
            diseñoTablero.setVisible(true);
        } else {
            DiseñoCaminoTab diseñoCaminoTab = new DiseñoCaminoTab(juegoC.getAlto(),juegoC.getLargo(),juegoC);         
            diseñoCaminoTab.setLocationRelativeTo(null);
            diseñoCaminoTab.setVisible(true);
        }
    }//GEN-LAST:event_btnTableroActionPerformed

    private void btnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralActionPerformed
        // TODO add your handling code here:
        DiseñoGeneralidad dGeneral;
         dGeneral = new DiseñoGeneralidad(juegoC);
        //this.setVisible(false);
        dGeneral.setLocationRelativeTo(null);
        dGeneral.setVisible(true);
    }//GEN-LAST:event_btnGeneralActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "Si sale se perderan todos los datos guradador \n ¿Desea salir aún?");
        if (opcion == JOptionPane.YES_OPTION) {
            cerrar();
        }        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetasActionPerformed
        // TODO add your handling code here:        
        if (juegoC.getTablero() == null || gruposPropiedad == null || grupoTT == null) {
            JOptionPane.showMessageDialog(null, "Tiene que terminar primero el tablero y tener al menos un grupo de toma tarjeta");
        } else{
        juegoC.setGrupoTT(grupoTT);
        juegoC.setGruposPropiedad(gruposPropiedad);
         CrearTarjetas tarjetas = new CrearTarjetas(juegoC);
        //this.setVisible(false);
        tarjetas.setLocationRelativeTo(null);
        tarjetas.setVisible(true);
        }
    }//GEN-LAST:event_btnTarjetasActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        if (juegoC.getGeneral() == null) {
            JOptionPane.showMessageDialog(null, "falta la generalidades");
        }
        if (juegoC.getTablero() == null) {
            JOptionPane.showMessageDialog(null, "falta el tablero");
        }
        if (juegoC.getTarjetas()== null) {
            JOptionPane.showMessageDialog(null, "faltan las tarjetas");
        }
        if (juegoC.getGeneral() != null && juegoC.getTablero() != null && juegoC.getTarjetas() != null) {
            JOptionPane.showMessageDialog(null, "Todo esta perfecto");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        juegoC.setGrupoTT(grupoTT);
        juegoC.setGruposPropiedad(gruposPropiedad);
        if (juegoC.getGeneral() != null && juegoC.getTablero() != null && juegoC.getTarjetas() != null) {
            RnWCrearJuego saveGameC = new RnWCrearJuego();
            try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Juego .board", "board"));
            fileChooser.setAcceptAllFileFilterUsed(false);
            int seleccion = fileChooser.showSaveDialog(this);
            if (seleccion == APPROVE_OPTION) {
                saveGameC.WriteGameC(fileChooser.getSelectedFile().getPath()+".board", juegoC);
                JOptionPane.showMessageDialog(null, "Se ha Guardado correctamente los datos");
                cerrar();                
            }
        } catch (HeadlessException | Exceptions e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Info", JOptionPane.ERROR_MESSAGE);
        }
        } else {
            JOptionPane.showMessageDialog(null, "Faltan datos, revisa con el boton de verificar");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void setEnablebtnGeneral(boolean estado){
        btnGeneral.setEnabled(estado);
    }
    public void setEnablebtnTablero(boolean estado){
        btnTablero.setEnabled(estado);
    }
    private void cerrar(){
        this.setVisible(false);
        Welcome welcome = new Welcome();
        welcome.setLocationRelativeTo(null);
        welcome.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGeneral;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTablero;
    private javax.swing.JButton btnTarjetas;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel lblTittle;
    // End of variables declaration//GEN-END:variables
}
