/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import Casillas.CasillaPropiedad;
import funcionalidades.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chejohrpp
 */
public class VisualPropiedades extends javax.swing.JFrame {
    private Jugadores jugador;
    private DefaultTableModel dfm = new DefaultTableModel();
    private CasillaPropiedad[] propiedades;
    /**
     * Creates new form VisualPropiedades
     */
    public VisualPropiedades(Jugadores jugador) {
        initComponents();
        this.jugador = jugador;
        this.propiedades = jugador.getPropiedades();
        dfm = (DefaultTableModel) tableLista.getModel();
        //System.out.println(jugador.getCantPropiedades());
        generar();
    }
    private void generar(){
              //Limpiar listado
       int cantRow = tableLista.getRowCount();
        if (cantRow > 1 ) {
            for (int i = cantRow-1; i >= 0; i--) {
                dfm.removeRow(i);
            }
        }        
        //Agregar listado
        if (jugador.getPropiedades() != null) {
            for (int i = 0; i < jugador.getPropiedades().length; i++) {
                
                if (propiedades[i].getCasillaLugar() != null) {
                    String[] data = {propiedades[i].getNombre(),String.valueOf(propiedades[i].getCosto()), propiedades[i].getTipoPropiedad(), String.valueOf(propiedades[i].getCasillaLugar().getCantCasas()),
                            String.valueOf(propiedades[i].getCasillaLugar().getCantHoteles()), estado(propiedades[i])};
                    dfm.addRow(data);
                } else {
                    String[] data = {propiedades[i].getNombre(),String.valueOf(propiedades[i].getCosto()), propiedades[i].getTipoPropiedad(), "No se puede construir", "No se puede"
                            + " construir" ,  estado(propiedades[i])};
                    dfm.addRow(data);
                }
                
            }
        }
    }
    private String estado(CasillaPropiedad propiedad){
        if (propiedad.isEstadoHipoteca() == false) {
            return "No Hipotecado";
        }
        return "Hipotecado";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mis propiedades");

        tableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Tipo", "Casas", "Hoteles", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tableLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLista;
    // End of variables declaration//GEN-END:variables
}
