/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontedPartida;

import Casillas.*;
import static frontend.PartidaGUI.juegoG;
import funcionalidades.*;
import javax.swing.JOptionPane;

/**
 *
 * @author chejohrpp
 */
public class VisualRecuperar extends javax.swing.JFrame {
    private Jugadores jugador;
    private double costo;
    private CasillaPropiedad propiedad;
    
    /**
     * Creates new form VisualRecuperar
     */
    public VisualRecuperar(Jugadores jugador) {
        this.jugador = jugador;
        initComponents();
        lblCosto.setVisible(false);
        generar();
    }
    private void generar(){
        if (jugador.getCantPropiedades() != 0) {
            for (int i = 0; i < jugador.getPropiedades().length; i++) {
                if (jugador.getPropiedades()[i].isEstadoHipoteca()) {
                    cmbRecuperar.addItem(jugador.getPropiedades()[i].getNombre());
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbRecuperar = new javax.swing.JComboBox<>();
        lblCosto = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Elija que propiedad desea recuperar de su hipoetca");

        cmbRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRecuperarActionPerformed(evt);
            }
        });

        lblCosto.setText("Costo: 000");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCosto)
                            .addComponent(cmbRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(268, 268, 268))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(cmbRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblCosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (cmbRecuperar.getSelectedIndex() == -1) {
            int opcion = JOptionPane.showConfirmDialog(null, "Seguro quieres recuperar la propiedad");
            if (opcion == JOptionPane.YES_OPTION) {
                if (jugador.getRiqueza() > costo) {
                    propiedad.setEstadoHipoteca(false);
                    jugador.setRiqueza((int) (jugador.getRiqueza() - costo));
                    jugador.setRiquezaTotal((int) (jugador.getRiquezaTotal() - costo));
                }else{
                    JOptionPane.showMessageDialog(null, "No tienes suficiente dinero para recuperarlo");
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRecuperarActionPerformed
        // TODO add your handling code here:
        if (cmbRecuperar.getSelectedItem() != null) {
            for (int i = 0; i < jugador.getPropiedades().length; i++) {
                if (cmbRecuperar.getSelectedItem().toString().equalsIgnoreCase(jugador.getPropiedades()[i].getNombre())) {
                    costo = jugador.getPropiedades()[i].getPrecioHipoteca() * juegoG.getJuegoC().getGeneral().getPorcentajeHipoteca() + jugador.getPropiedades()[i].getPrecioHipoteca();
                    propiedad = jugador.getPropiedades()[i];
                    lblCosto.setText("Costo de recuperacion es de $" + costo);
                    lblCosto.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_cmbRecuperarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cmbRecuperar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCosto;
    // End of variables declaration//GEN-END:variables
}
